### PR TITLE
Update multi_sort.dart

### PR DESCRIPTION
**Pull request by brunodmn**
Hi, 
 It's a great job so far, I propose some extra sorting supports by datetime, string, enum and bool. I needed it, so a made, if you thing its interesting could add on package too.

Thanks

### CODE REVIEW

**Comment by kkulikowski** [comment]
works flawlessly for me mate, thanks!

**Comment by deependra227** [comment]
Hi @brunodmn,
Thanks for raising the issue and for the solution as well. I appreciate it.
I just wanted to know have you gone through issue #2. Is it not working for you?

**Comment by brunodmn** [comment]
> Hi @brunodmn,
> Thanks for raising the issue and for the solution as well. I appreciate it.
> I just wanted to know have you gone through issue #2. Is it not working for you?

Hello dear,

 Sorry, I did not see that issue before, but was exactly that error I had with datetime that made me change the code a little bit, so I suppose it will work with new pull request and MultiSortType.generic.

**Comment by deependra227** [comment]
I haven't updated the file yet,  that's why you are getting the error. But DateTime is also supported ([compareTo Method](https://api.dart.dev/stable/2.12.2/dart-core/DateTime/compareTo.html)) just by referring to #2. I would be grateful if you can confirm it. If that doesn't work, I'll be happy to merge your pull request.

**Comment by brunodmn** [comment]
Yes, works with datetime too, wait a little bit, I am improving the code, I'd like to make it more generic, so user would not need to pass parameters others than preference..working on it right now so you can check...

**Comment by brunodmn** [comment]
Hi, check now.
I don't understand why criteria were dynamic, changed to List<String>. If it really needs to be dynamic, assert won't be able to get preference.length.
 I checked with datetime too and worked well even with generic type, as timestamp number become a string to be sorted.

**Comment by deependra227** [comment]
Why you have made cases for the data types (DateTime, enum, generic). #2 (compareTo method) supports all types of data types. It is already generic. Correct me if I am wrong. 
I really appreciate your time and effort. But you are not improving the code, you are just adding unnecessary code/conditions.

**Comment by brunodmn** [comment]
I did it to have more control over the sort order, initially I coded to compare datetime,  compareTo supports only String as parameter. 
Some objects will work fine if you convert toString and sort, some won't. 
 Anyway, you can remove MultiSortType, convert all to string and compareTo, I quickly tested for datetime, string, numbers, bools, enums and it seems fine, code will look like:
```
library multi_sort;

extension MultiSort on List {
  multisort(List<String> preference, {List<bool> criteria}) {
    assert((preference.length > 0),
        'MultiSort: Preference lenght must NOT me empty.');

    if (criteria != null) {
      assert((criteria.length == preference.length),
          'MultiSort: Criteria list has to be same size as preference list.');
    }

    int compare(int i, dynamic a, dynamic b) {
      bool _criteria = criteria == null ? true : criteria[i];

      try {
        return _criteria
            ? a
                .get(preference[i])
                .toString()
                .toLowerCase()
                .compareTo(b.get(preference[i]).toString().toLowerCase())
            : b
                .get(preference[i])
                .toString()
                .toLowerCase()
                .compareTo(a.get(preference[i]).toString().toLowerCase());
      } catch (e) {
        print(
            'MultiSort: Error, $e');
        return 0;
      }
    }

    int sortall(a, b) {
      int i = 0;
      int result;
      while (i < preference.length) {
        result = compare(i, a, b);
        if (result != 0) break;
        i++;
      }
      return result;
    }

    this.sort((a, b) => sortall(a, b));
  }
}

```

**Pull request closed without merging**
